header = "sys/types.h"

types = ["dev_t",
         "uid_t",
         "gid_t",
         "ino_t",
         "mode_t",
         "nlink_t",
         "off_t",
         "pid_t",
         "clock_t",
         "id_t",
         "time_t",
         "suseconds_t",
         "key_t",
         "clockid_t",
         "timer_t",
         "blksize_t",
         "blkcnt_t",
         "fsblkcnt_t",
         "fsfilcnt_t",
         "pthread_t",
         "pthread_attr_t",
         "pthread_mutex_t",
         "pthread_mutexattr_t",
         "pthread_cond_t",
         "pthread_condattr_t",
         "pthread_key_t",
         "pthread_once_t",
         "pthread_rwlock_t",
         "pthread_rwlockattr_t",
         "pthread_spinlock_t",
         "pthread_barrier_t",
         "pthread_barrierattr_t",
         ]
