header = "sys/ipc.h"

types = ["ipc_perm",
         ]

ints = ["IPC_CREAT",
        "IPC_EXCL",
        "IPC_NOWAIT",
        "IPC_PRIVATE",
        "IPC_RMID",
        "IPC_SET",
        "IPC_STAT",
        ]
