header = "netdb.h"

types = ["netent",
         "hostent",
         "servent",
         "protoent",
         "addrinfo",
         ]

ints = ["IPPORT_RESERVED",
        "AI_PASSIVE",
        "AI_CANONNAME",
        "AI_NUMERICHOST",
        "AI_NUMERICSERV",
        "AI_V4MAPPED",
        "AI_ALL",
        "AI_ADDRCONFIG",
        "NI_NOFQDN",
        "NI_NUMERICHOST",
        "NI_NAMEREQD",
        "NI_NUMERICSERV",
        "NI_DGRAM",
        "EAI_AGAIN",
        "EAI_BADFLAGS",
        "EAI_FAIL",
        "EAI_FAMILY",
        "EAI_MEMORY",
        "EAI_NONAME",
        "EAI_SERVICE",
        "EAI_SOCKTYPE",
        "EAI_SYSTEM",
        "EAI_OVERFLOW",
        ]
