header = "stropts.h"

types = ["t_scalar_t",
         "t_uscalar_t",
         "bandinfo",
         "strbuf",
         "strpeek",
         "strfdinsert",
         "strioctl",
         "strrecvfd",
         "str_mlist",
         "str_list",
         ]

ints = ["I_ATMARK",
        "I_CANPUT",
        "I_CKBAND",
        "I_FDINSERT",
        "I_FIND",
        "I_FLUSH",
        "I_FLUSHBAND",
        "I_GETBAND",
        "I_GETCLTIME",
        "I_GETSIG",
        "I_GRDOPT",
        "I_GWROPT",
        "I_LINK",
        "I_LIST",
        "I_LOOK",
        "I_NREAD",
        "I_PEEK",
        "I_PLINK",
        "I_POP",
        "I_PUNLINK",
        "I_PUSH",
        "I_RECVFD",
        "I_SENDFD",
        "I_SETCLTIME",
        "I_SETSIG",
        "I_SRDOPT",
        "I_STR",
        "I_SWROPT",
        "I_UNLINK",
        "FMNAMESZ",
        "FLUSHR",
        "FLUSHRW",
        "FLUSHW",
        "S_BANDURG",
        "S_ERROR",
        "S_HANGUP",
        "S_HIPRI",
        "S_INPUT",
        "S_MSG",
        "S_OUTPUT",
        "S_RDBAND",
        "S_RDNORM",
        "S_WRBAND",
        "S_WRNORM",
        "RS_HIPRI",
        "RMSGD",
        "RMSGN",
        "RNORM",
        "RPROTDAT",
        "RPROTDIS",
        "RPROTNORM",
        "SNDZERO",
        "ANYMARK",
        "LASTMARK",
        "MORECTL",
        "MOREDATA",
        "MSG_ANY",
        "MSG_BAND",
        "MSG_HIPRI",
        ]
