header = "fmtmsg.h"

longs = ["MM_NOSEV",
         "MM_HALT",
         "MM_ERROR",
         "MM_WARNING",
         "MM_INFO",
         "MM_OK",
         "MM_NOTOK",
         "MM_NOMSG",
         "MM_NOCON",
         "MM_HARD",
         "MM_SOFT",
         "MM_FIRM",
         "MM_APPL",
         "MM_UTIL",
         "MM_OPSYS",
         "MM_RECOVER",
         "MM_NRECOV",
         "MM_PRINT",
         "MM_CONSOLE",
         ]
