header = "sys/resource.h"

types = ["rlim_t",
         "rlimit",
         "rusage",
         ]

ints = ["PRIO_PROCESS",
        "PRIO_PGRP",
        "PRIO_USER",
        "RUSAGE_SELF",
        "RUSAGE_CHILDREN",
        "RLIMIT_CORE",
        "RLIMIT_CPU",
        "RLIMIT_DATA",
        "RLIMIT_FSIZE",
        "RLIMIT_NOFILE",
        "RLIMIT_STACK",
        "RLIMIT_AS",
        ]

[[custom]]
c_type = "rlim_t"
rs_type = "rlim_t"
vars = ["RLIM_INFINITY",
        "RLIM_SAVED_MAX",
        "RLIM_SAVED_CUR",
        ]
