header = "regex.h"

types = ["regex_t",
         "regoff_t",
         "regmatch_t",
         ]

ints = ["REG_EXTENDED", 
        "REG_ICASE",    
        "REG_NOSUB",    
        "REG_NEWLINE",  
        "REG_NOTBOL",   
        "REG_NOTEOL",   
        "REG_NOMATCH",  
        "REG_BADPAT",   
        "REG_ECOLLATE", 
        "REG_ECTYPE",   
        "REG_EESCAPE",  
        "REG_ESUBREG",  
        "REG_EBRACK",   
        "REG_EPAREN",   
        "REG_EBRACE",   
        "REG_BADBR",    
        "REG_ERANGE",   
        "REG_ESPACE",   
        "REG_BADRPT",   
        ]
