header = "sys/socket.h"

types = ["socklen_t",
         "sa_family_t",
         "sockaddr",
         "sockaddr_storage",
         "msghdr",
         "cmsghdr",
         "linger",
         ]

ints = ["SHUT_RD",
        "SHUT_WR",
        "SHUT_RDWR",
        "AF_INET",
        "AF_INET6",
        "AF_UNIX",
        "AF_UNSPEC",
        "SOL_SOCKET",
        "SO_ACCEPTCONN",
        "SO_BROADCAST",
        "SO_DEBUG",
        "SO_DONTROUTE",
        "SO_ERROR",
        "SO_KEEPALIVE",
        "SO_LINGER",
        "SO_OOBINLINE",
        "SO_RCVBUF",
        "SO_RCVLOWAT",
        "SO_RCVTIMEO",
        "SO_REUSEADDR",
        "SO_SNDBUF",
        "SO_SNDLOWAT",
        "SO_SNDTIMEO",
        "SO_TYPE",
        "SOMAXCONN",
        ]

uints = ["SOCK_STREAM",
         "SOCK_DGRAM",
         "SOCK_RAW",
         "SOCK_SEQPACKET",
         "MSG_OOB",
         "MSG_PEEK",
         "MSG_DONTROUTE",
         "MSG_CTRUNC",
         "MSG_TRUNC",
         "MSG_EOR",
         "MSG_WAITALL",
         "MSG_NOSIGNAL",
         "SCM_RIGHTS",
         ]
