header = "utmpx.h"

types = ["utmpx",
         ]

shorts = ["EMPTY",
          "BOOT_TIME",
          "OLD_TIME",
          "NEW_TIME",
          "USER_PROCESS",
          "INIT_PROCESS",
          "LOGIN_PROCESS",
          "DEAD_PROCESS",
          ]
