header = "ftw.h"

types = ["FTW",
         ]

ints = ["FTW_F",
        "FTW_D",
        "FTW_DNR",
        "FTW_DP",
        "FTW_NS",
        "FTW_SL",
        "FTW_SLN",
        "FTW_PHYS",
        "FTW_MOUNT",
        "FTW_DEPTH",
        "FTW_CHDIR",
        ]
