header = "signal.h"

types = ["sig_atomic_t",
         "sigset_t",
         "sigevent",
         "sigval",
         "sigaction",
         "mcontext_t",
         "ucontext",
         "stack_t",
         "siginfo_t",
         ]

ints = ["SIGEV_NONE",
        "SIGEV_SIGNAL",
        "SIGEV_THREAD",
        "SIGABRT",
        "SIGALRM",
        "SIGBUS",
        "SIGCHLD",
        "SIGCONT",
        "SIGFPE",
        "SIGHUP",
        "SIGILL",
        "SIGINT",
        "SIGKILL",
        "SIGPIPE",
        "SIGQUIT",
        "SIGSEGV",
        "SIGSTOP",
        "SIGTERM",
        "SIGTSTP",
        "SIGTTIN",
        "SIGTTOU",
        "SIGUSR1",
        "SIGUSR2",
        "SIGPOLL",
        "SIGPROF",
        "SIGSYS",
        "SIGTRAP",
        "SIGURG",
        "SIGVTALRM",
        "SIGXCPU",
        "SIGXFSZ",
        "SIG_BLOCK",
        "SIG_UNBLOCK",
        "SIG_SETMASK",
        "SA_NOCLDSTOP",
        "SA_ONSTACK",
        "SA_RESETHAND",
        "SA_RESTART",
        "SA_SIGINFO",
        "SA_NOCLDWAIT",
        "SA_NODEFER",
        "SS_ONSTACK",
        "SS_DISABLE",
        "MINSIGSTKSZ",
        "SIGSTKSZ",
        "ILL_ILLOPC",
        "ILL_ILLOPN",
        "ILL_ILLADR",
        "ILL_ILLTRP",
        "ILL_PRVOPC",
        "ILL_PRVREG",
        "ILL_COPROC",
        "ILL_BADSTK",
        "FPE_INTDIV",
        "FPE_INTOVF",
        "FPE_FLTDIV",
        "FPE_FLTOVF",
        "FPE_FLTUND",
        "FPE_FLTRES",
        "FPE_FLTINV",
        "FPE_FLTSUB",
        "SEGV_MAPERR",
        "SEGV_ACCERR",
        "BUS_ADRALN",
        "BUS_ADRERR",
        "BUS_OBJERR",
        "TRAP_BRKPT",
        "TRAP_TRACE",
        "CLD_EXITED",
        "CLD_KILLED",
        "CLD_DUMPED",
        "CLD_TRAPPED",
        "CLD_STOPPED",
        "CLD_CONTINUED",
        "POLL_IN",
        "POLL_OUT",
        "POLL_MSG",
        "POLL_ERR",
        "POLL_PRI",
        "POLL_HUP",
        "SI_USER",
        "SI_QUEUE",
        "SI_TIMER",
        "SI_ASYNCIO",
        "SI_MESGQ",
        ]
