header = "float.h"

ints = ["FLT_RADIX",
        "FLT_MANT_DIG",
        "DBL_MANT_DIG",
        "LDBL_MANT_DIG",
        "FLT_DIG",
        "DBL_DIG",
        "LDBL_DIG",
        "FLT_MIN_EXP",
        "DBL_MIN_EXP",
        "LDBL_MIN_EXP",
        "FLT_MIN_10_EXP",
        "DBL_MIN_10_EXP",
        "LDBL_MIN_10_EXP",
        "FLT_MAX_EXP",
        "DBL_MAX_EXP",
        "LDBL_MAX_EXP",
        "FLT_MAX_10_EXP",
        "DBL_MAX_10_EXP",
        "LDBL_MAX_10_EXP",
        ]
